export const GET_LIST_REQUEST = "TODO/GET_LIST_REQUEST";
export const GET_LIST_SUCCESS = "TODO/GET_LIST_SUCCESS";
export const GET_LIST_FAILURE = "TODO/GET_LIST_FAILURE";

export const GET_REQUEST = "TODO/GET_REQUEST";
export const GET_SUCCESS = "TODO/GET_SUCCESS";
export const GET_FAILURE = "TODO/GET_FAILURE";

export const ADD_REQUEST = "TODO/ADD_REQUEST";
export const ADD_SUCCESS = "TODO/ADD_SUCCESS";
export const ADD_FAILURE = "TODO/ADD_FAILURE";

export const DELETE_REQUEST = "TODO/DELETE_REQUEST";
export const DELETE_SUCCESS = "TODO/DELETE_SUCCESS";
export const DELETE_FAILURE = "TODO/DELETE_FAILURE";

export const EDIT_REQUEST = "TODO/EDIT_REQUEST";
export const EDIT_SUCCESS = "TODO/EDIT_SUCCESS";
export const EDIT_FAILURE = "TODO/EDIT_FAILURE";